### ISSUE TITLE
Slide up and slide down animation

### ISSUE THREAD

**Issue by rgllm** [springload/react-accessible-accordion#127]
Hello.

After researching for a while I can't discover how to add an animation to slide up and slide down.
Like this accordion: https://codepen.io/anon/pen/mGgRRr

Can you please help me?

**Comment by ryami333** [comment]
Gidday @rgllm,

While we do publish some basic boilerplate styles to help get people started, animation and transitions fall oustide the scope of this project - we deliberately leave these details up to the user to implement. I've not personally attempted this kind of sliding animation with our accordion because of the reflow issues it would likely cause on long webpages. But if I were to try, I would probably use this library in combination with a 'FLIP' animation library (like [this one](https://github.com/joshwcomeau/react-flip-move), for example). Also keep in mind that you can leverage the `className` and `hideBodyClassName` props in order to apply different styles to your accordion components when they are open or closed.

Sorry I can't be of more help @rgllm. I'm going to close this issue, but I'm happy to discuss further :)
