### ISSUE TITLE
Proposal: Component naming changes

### ISSUE THREAD

**Issue by ryami333** [springload/react-accessible-accordion#150]
The WAI-ARIA [spec](https://www.w3.org/TR/wai-aria-practices-1.1/#accordion) uses specific language "Accordion Heading" and "Accordion Panel" to identify the markup required in order to author an 'accordion' component. We have subtly different naming conventions, and it might pay to align them to remove ambiguity.

#### Proposal 1a:

Rename `AccordionItemTitle` to `AccordionItemHeading`.

#### Proposal 1b:

Rename `AccordionItemBody` to `AccordionItemPanel`.

### Implications

We could implement this as a breaking change, OR as a deprecation (by exporting to both the old _and_ new component names, but with warnings for the old names).

**Comment by samanthaksanders** [comment]
Yes, alignment would be nice. The panel one, for sure I would rename without any issues. 

The heading one is a little tricky, only that I have not always been sure we were executing the requirements quite right according to the specs. But I believe there was a reason for why it's done the way it is.

Spec says that the button should be inside a heading (either using native element or role heading and aria level), but we haven't done this. And I think maybe it was to make our code less opinionated so that developers can choose the right heading element for themselves depending on the hierarchy of their own project. This approach is reliant on developers using the right markup inside the title.

It would be worth investigating if this current implementation would fail testing. 

If our current approach were to fail,  it may be that we do need to force an element with role heading and give the developers the option to choose what level it is to fit with their project 😬 and then include the element with role button inside there. Would be pretty rigid though.

As for the implications, depends on how hard line approach we wanna take. It gets a few downloads in a week, maybe a warning for the old would be a good start?

**Comment by ryami333** [comment]
Thanks for your comments @samanthaksanders :) That's interesting, and that's a good idea re: using `<hx />` elements in AccordionItemTitle/AccordionItemHeading with a prop to choose `h1|h2|h3|h4|h5|h6`. What should the default be?? 😓 

Just to play devil's advocate...

>  It gets a few downloads in a week

I think that's a bit of a moot point. The difference between 'deprecation' and 'breaking-change' only affects people _upgrading_ from 2.X to 3.X, not new installs. It's difficult (impossible?) to track how many people upgrade, and how often. BUT... that doesn't mean I disagree with the idea of deprecation... 😛

**Comment by samanthaksanders** [comment]
Level 3 default seems the most sensible i'd say. Might actually be worth sourcing some further advice on this one though. There are several different ways we could reimplement this. 

My gut instinct always tells me to use native elements like an actual heading element and an actual button. But as you say, it would definitely be a breaking change. And probably more restrictive for developers. 

We are already missing a few things from the spec though, like all the correct keyboard functionality. So a massive rewrite of "breaking changes" is actually probably for the best.

Ideally you'd want it to output something like this:
```
<div role="heading" aria-level="X">
	<button type="button" id="accordionButtonX" aria-expanded="true/false" aria-controls="panelX">
		Title goes here 
		[ can also include any element considered "phrasing content" ]
	</button>
</div>
<div id="panelX" aria-labelledby="accordionButtonX" role="region">
	Panel content goes here
</div>
```

**Comment by ryami333** [comment]
Also - I think we should probably move most of the sentiment of this issue to a separate one. We should be considering a review of the markup API _whether or not_ we change the names of these components (which it seems you agree we should).
