### ISSUE TITLE
list Supported browser / device versions (not just latest)

### ISSUE THREAD

**Issue by friedz** [springload/react-accessible-accordion#185]
*latest* is not a useful version

**Comment by ryami333** [comment]
@friedz - thanks for your issue :)

Sorry if you don't don't find it useful, but that list is about as descriptive as we can make it. I am not going to enumerate specific versions for each of those browsers (except IE) because I don't want to commit our maintainers (which us mostly just me at this time 😅) to fielding queries/issues relating to old browsers which we don't have the tools to test ourselves.

If you're using an evergreen browser, and you're behind a few versions, then this library will _very likely_ work, but we can't help you if some browser-bug prevents it from doing so, so yes we only support the latest versions of those browsers.

**Comment by friedz** [comment]
Could you just list the versions you test it in or something like that, so i could just compare to the version of my browser if its the same or newer, right now it is completely useless.

I totally get that you don't have the capacity to test for every browser out there in every version, but maybe you could just write the version number for latest instead of "latest" that wouldn't really change much for you but is far more useful.

**Comment by ryami333** [comment]
@friedz unfortunately there is a fatally false assumption you've made which is that we physically (or by way of automation) test _all_ functionality with the infinite combinations and across multiple browsers before we do a release. We, and indeed most library publishers don't actually do this. Instead, we leverage a few different technologies:

### Transpilation

We transpile our code with `babel` and `@babel/preset-env` to assert that the code itself is compliant with our specified browsers to a reasonable degree of confidence. The browsers are specified in `.browserslistrc`.

### Unit testing

We use Jest and Enzyme to assert that our components behave how we expect, for a large number of input combinations and permutations.

### End-to-end testing

We use Puppeteer (headless Chrome) to assert that our project adheres to and complies with the WAI-ARIA spec to an 'Accordion', and to assert that the project works in a real browser environment under real browser conditions.

---

So as you can see - our browser support claims are informed extrapolations. There's no point specifying exact versions, because that would imply that we've hand tested on those exact versions. And *ultimately* the support list is just _that_, a _support_ list: if you have an issue on an unsupported browser, then we will not _support_ you.
