### ISSUE TITLE
Arrows are not displayed

### ISSUE THREAD

**Issue by sebastiansuciu** [springload/react-accessible-accordion#186]
Hello,

I deal with arrow problem, is not showing up.

Here is my code:
![image](https://user-images.githubusercontent.com/38329524/53020794-648d5700-3460-11e9-8841-2f640f7774b3.png)
And the inspect element
![image](https://user-images.githubusercontent.com/38329524/53020835-7969ea80-3460-11e9-8ae4-b835dff7612e.png)

Could you help me to get a workaround?
Thank you,
Sebastian.

**Comment by ryami333** [comment]
Gidday @sebastiansuciu, thanks for your issue.

I presume that you are using `fancy-example.css` and wondering why arrows aren't being shown? That's probably because you need to add the markup for the arrows themselves (divs with `className="accordion__arrow"`. See the [code for our demo page](https://github.com/springload/react-accessible-accordion/blob/504fd143370769c03e5cf89a9ca0b6733dd49419/demo/js/demo.tsx#L24) for an example.

**Comment by sebastiansuciu** [comment]
Thank you, I couldn't find that in the documentation, is clear now. Thanks.
