### ISSUE TITLE
AccordionItemBody

### ISSUE THREAD

**Issue by patrykbuda** [springload/react-accessible-accordion#205]
Hello, I have just a question whether is it possible to modify the html structure of AccordionItemBody
currently it generates ul-> li structure. I would like to use flexbox there to better position elements inside that. Thanks in advance :)

**Comment by ryami333** [comment]
Gidday @patrykbuda, thanks for your issue. First of all, would you please upgrade to the latest version `react-accessible-accordion` which exports `AccordionItemPanel` instead of `AccordionItemBody`. That aside, I'm still not sure what your issue is - even in `2.X.X` we used `div`s for `AccordionItemBody`, not `li` or `ul`s. Could you please create a Codesandbox to demonstrate and reproduce your issue?

**Comment by patrykbuda** [comment]
@ryami333 Thank you seems like I have just missed my component which was wrapped by AccordionItemBody and that caused that behavior all clear now. Thank you for a version bump suggestion which I have just implemented this can be now closed :)
