### ISSUE TITLE
How do i remove the default blue border that is displayed on click of an AccordionItem? 

### ISSUE THREAD

**Issue by hjagannathan** [springload/react-accessible-accordion#206]
How do i remove the default blue border that is displayed on click of an AccordionItem? I am newbie to react. Please help!

**Comment by ryami333** [comment]
Gidday @hjagannathan - thanks for your good question :) That blue `outline` is applied by your browser (not this package) to the element which has focus. For accessibility purposes, we don't recommend that you remove that outline entirely, because users with motor impairments who navigate entirely by keyboard (or other assistive technology). _However_, I've used packages like [`what-input`](https://github.com/ten1seven/what-input) to great success, by disabling that outline ONLY in the case that the user is using mouse/touch input.

I typically do the following:
```js
// main.js

import 'what-input';
```

```
// main.css

[data-whatinput='mouse'] :focus,
[data-whatinput='touch'] :focus {
    outline: none;
}
```

**Comment by hjagannathan** [comment]
Thank you so much. It worked. :)
