### ISSUE TITLE
Expand AccordionItem programmatically (preExpanded not working properly after clicking an AccordionItem)

### ISSUE THREAD

**Issue by harunozceyhan** [springload/react-accessible-accordion#207]
Hi,
Thanks for a great component.
 I try to expand AccordionItem programmatically but I cant with **v3.0.0.**
"**preExpanded**" property working properly at start but after clicking an item, changing preExpanded array not updating the Accordion and not expanding the AccordionItem.
In short, I need to expand the items programmatically at any time and any state... Is there any other way to do it ?

Thanks.

**Comment by ryami333** [comment]
Gidday @harunozceyhan, thanks for your issue :) I presume that you've closed this issue because you've found [these notes](https://github.com/springload/react-accessible-accordion#which-design-patterns-does-this-component-not-aim-to-solve) in our README or perhaps the discussion in [this issue](https://github.com/springload/react-accessible-accordion/issues/174).

**Comment by harunozceyhan** [comment]
Yes, I've found the notes in README. Actually I found a way to do it :) Thanks again for the component. Take care !

**Comment by madhuwudali** [comment]
Hello - I am trying to do the same. Can you let me know how you fixed it?

Thanks

**Comment by harunozceyhan** [comment]
Hi madhuwudali,

Unfortunately, I don't remember how I did it and I don't have access rights to code anymore since I was working on that project as freelance developer. Sorry to say that :(
