### ISSUE TITLE
Set expanded items

### ISSUE THREAD

**Issue by dgavara** [springload/react-accessible-accordion#212]
Hi,
How can we set expanded items after initial render. I can only set preExpanded which works only on mount.

**Comment by ryami333** [comment]
Gidday @dgavara, thanks for your issue. We don't currently support programmatic toggling of expanded/disabled state, because it _implies_ (at least in our opinion) that RAA is being re-purposed in an in-accessible way. See [here](https://github.com/springload/react-accessible-accordion/issues/174) for the full justification, or to add your use-case to convince us to add this functionality!

**Comment by dgavara** [comment]
HI @ryami333. The use case is I am dynamically adding the accordian sections when user adds a search filter (companies in my case). So i have to close all the opened sections and just expand the last seaction. Please let me know if this is possible?

**Comment by mledwards** [comment]
This feels like a useful feature to be able to set preExpanded dynamically.
