### ISSUE TITLE
Do we have option to collapse/Expand all feature

### ISSUE THREAD

**Issue by rasheedqadar** [springload/react-accessible-accordion#214]
How can we handle the feature to collapse/Expand all in react-accessible-accordion.

Please let me know If there is any existing code.

Thanks

**Comment by bozazec** [comment]
I need this feature too, or to be able manually to control expand/collapse of items

**Comment by ryami333** [comment]
Hi there @rasheedqadar and @bozazec, sorry for the delay in getting back to you. The decision not to include an API for manual control of accordion item state is a deliberate design decision, and you can find a broad justification for that decision in the conversation [here](https://github.com/springload/react-accessible-accordion/issues/174). The TL;DR is that it's a good indication that you're not making a truly accessible accordion as per the WAI-ARIA spec.

The "expand/collapse-all" use-case is an interesting one. One solution would be to take advantage of the `key` prop which you can pass to _any_ react component. When you pass a different value you force it to completely re-mount. You could use that `key` prop in conjunction with the `Accordion` component's `preExpanded` prop in order to force a complete update of the state of all the items.

Hope this helps!

**Comment by manojkumar3692** [comment]
Can you please drop a example of how to do it. That would be a great help @ryami333
