### ISSUE TITLE
Custom component integration

### ISSUE THREAD

**Issue by andrew-aladev** [springload/react-accessible-accordion#216]
[Divs](https://github.com/springload/react-accessible-accordion/blob/master/src/components/Accordion.tsx#L37) makes these components unusable within table.

Please add ability to pass any custom component instead of just div, like:

```
component: PropTypes.oneOfType([PropTypes.func, PropTypes.string]).isRequired
...
static defaultProps = {
    component: 'div'
...
<component .../>
```

**Comment by ryami333** [comment]
Gidday @andrew-aladev, thanks for your feedback. Could you please send me some pseudo-code demonstrating what exactly you'd like to do? My gut tells me that this would be a Bad Idea™ because you could end up inadvertently breaking your table's screen-reader compliance. RAA applies `role=region|heading|button` to various component, which could (would) clobber the inherent `table|rowgroup|row|cell` roles of native table elements. In other words, this aspect of the API is somewhat deliberately rigid.

**Comment by andrew-aladev** [comment]
Hello. I am against hardcoding `div` inside each component.

`Accordion` can be `tbody`, `AccordionItem` can be `Fragment`, `AccordionItemTitle` can be `tr` with title and `AccordionItemBody` can be `tr` with data.

Anyway people can use any other custom components.

**Comment by ryami333** [comment]
No @andrew-aladev that's not true, `AccordionItemTitle` can not be a `tr` and nor can an `AccordionItemBody`. Actually, to be strictly correct, it's the inverse that is true, let me explain...

If we had this API:
```jsx
<AccordionItemTitle component="tr" />
```
It would render markup which looks like this:
```jsx
<tr role="heading" />
```

Do you see the problem with that output? The `tr` element has an implicit role (`tablerow`) which it needs in order to be such in the context of a table. By adding the `role="heading"` attribute, we're clobbering/overriding that implicit role, and therefore by permitting this pattern we could end up inadvertently invalidating users' table spec-compliance, even if we would be maintaining the _accordion's_ spec compliance.

Note though, that if you're just trying to achieve _table-like_ layout, then you can still use `display: table-row` on these components.

Note also, that you're correct in identifying that `Accordion` and `AccordionItem` are, for all intents and purposes, just "context providers" and they could even render Fragments instead of `div`s. It was a difficult API design decision to choose `div`s instead. We may consider exposing `AccordionProvider` and `AccordionItemProvider` components as alternatives to `Accordion` and `AccordionItem` respectively.

Thanks again for your input @andrew-aladev - I'm going to close this issue now because I don't think there's anything actionable here right now, but feel free to continue to discussion if you feel that there's something which we haven't thought of!

**Comment by andrew-aladev** [comment]
> The tr element has an implicit role (tablerow) which it needs in order for a screenreader to identify it as such in the context of a table
You are trying to understand what people can do based on library, wrong way. If user wants to make a table layout - it is his pain.

> Therefore by permitting this pattern we could end up inadvertently invalidating users' tables' spec-compliance, even if we would technically still be maintaining the accordion's spec compliance.
You will still maintain default div layout.

You don't need to make a decision about what component will people use and what problems they can receive. You are just writing: `defaultProps = { component: 'div' }`. It means that you made a decision to use div based layout and it is ok.

Today nobody can extend `AccordionItem` (for example), because of hardcoded `div` inside. People have to make a fork, add generic component and extend it after.

**Comment by ryami333** [comment]
I believe you have either misread or fundamentally misunderstood my last message, so I suggest that you read it again carefully and you go away and read about both the [accordion spec](https://www.w3.org/TR/wai-aria-practices-1.1/#accordion) and the [table spec](https://www.w3.org/TR/wai-aria-practices-1.1/#table), because once you comprehend those you will understand that the use-case you have presented will objectively result in non-compliant markup.

The principal concern of this library is to assist users in implementing accessible design patterns, and we have made concerted decisions not to implement APIs which allow the library to be easily mispurposed (like in the example you've given) resulting in inaccessible markup (like in the example you've given). Doing so would go against the [core principals](https://github.com/springload/react-accessible-accordion/blob/master/CONTRIBUTING.md#project-principles) of the project.

**Comment by andrew-aladev** [comment]
> I believe you have either misread or fundamentally misunderstood my last message, so I suggest that you read it again carefully and you go away and read about both the accordion spec and the table spec, because once you comprehend those you will understand that the use-case you have presented will objectively result in non-compliant markup.

Sorry, but compliant or not compliant table markup will be - it is job for end-interface developer, not a job for library developers. Customer itself can ignore compliance if wide browser compatibility is more important for him.

> The principal concern of this library is to assist users in implementing accessible design patterns, and we have made concerted decisions not to implement APIs which allow the library to be easily mispurposed (like in the example you've given) resulting in inaccessible markup (like in the example you've given). Doing so would go against the core principals of the project.

You can't protect user by forcing `div`. `Accordion` can be `details` or `section`, `AccordionItemTitle` can be `summary` or `header`, some components can become just `Fragment` with custom props distribution. You can only prohibit to use semantic web or just something more pretty than div layout.

**Comment by ryami333** [comment]
> compliant ... markup ... not a job for library developers
That is, in fact, the exact purpose of this library: to abstract away a markup pattern which is otherwise cumbersome to make spec-compliant. 

> You can't protect user by forcing `div`
Well, evidently, we _can_. This issue serves as evidence of that - we have protected at least one user (you) from implementing non-compliant table markup.

> browser compatibility
... has almost nothing to do with this. RAA aims to solve aria-spec compliance, not w3 spec-compliance.

> `AccordionItemTitle` can be `summary`
No, it _can't_, not without invalidating your `summary` elements. Using `tr` as an example above, I've already explained in great detail why we won't permit this pattern. I'm not going to continue to debate over every individual HTML5 element one at a time.

I sense that this conversation is going nowhere, and that you still fundamentally misunderstand the purposes of this library. I direct you once more to the [aria spec](https://www.w3.org/TR/wai-aria-practices-1.1/#accordion), [this section](https://github.com/springload/react-accessible-accordion#which-design-patterns-does-this-component-aim-to-solve) of our README, and our [project principles](https://github.com/springload/react-accessible-accordion/blob/master/CONTRIBUTING.md#project-principles), before locking this issue to prevent it from devolving further.
