### ISSUE TITLE
How to allow only one item to be open at a time?

### ISSUE THREAD

**Issue by craigcosmo** [springload/react-accessible-accordion#232]
How to allow only one item to be open at a time? I want when I open other button, the previous opened should be autoclose

I tried this setting, seem missing something
```js
<Accordion
					key={index}
					allowMultipleExpanded={false}
					allowZeroExpanded={true}>
```

**Comment by ryami333** [comment]
Hi there @craigcosmo - the only-one-open-at-time behaviour is the default behaviour. Are you able to create a minimal example in [Codesandbox](https://codesandbox.io/) (for example) to demonstrate the issue that you are experiencing?

Otherwise, you can see examples for different behaviours on our [demo page](https://springload.github.io/react-accessible-accordion/) and view the source for those examples [here](https://github.com/springload/react-accessible-accordion/blob/master/demo/src/index.tsx).

**Comment by craigcosmo** [comment]
I found out why. I made many accordions. I thought I made the items inside accordion
