### ISSUE TITLE
The functionality that expanding one element will collapse another is not communicated to screenreaders.

### ISSUE THREAD

**Issue by CoraDale** [springload/react-accessible-accordion#286]
Testing on chrome with voiceover: https://react-accessible-accordion.springload.co.nz/

To the screenreader, each accordion item header is just a button that is either expanded or collapsed, the fact that expanding one collapses the previously opened item is not made clear to a screenreader, they will have to discover that themselves when they attempt to navigate back to the previously opened item.

**Comment by holloway** [comment]
@CalinDale is this functionality that we're missing per the WAI ARIA spec or is this behaviour that you think would be nice to have?

**Comment by CalinDale** [comment]
@holloway It's not against ARIA spec but it's a usability issue. The user shouldn't be changing the page content without knowing it.

**Comment by holloway** [comment]
@CalinDale  I suppose a potential issue with adding (eg) `aria-live` functionality to announce things is that screen readers could get better at accordions and announce these things and we'd be doubling up on the announcements.

Thanks for raising this .. I'll leave this ticket open and give it some thought, and look into the pros and cons of adding something that screen readers should probably do themselves.

**Comment by CalinDale** [comment]
@holloway Yeah I'm not sure of a good fix either. Aria-live would be overkill, better to inform the user before they touch the control.
Probably there should be a label explaining that expanding one element will collapse another. This could either go on the containing element around the whole accordion, or on each button?

Probably the best option would be to put that label on the collapsed buttons, but only if something is currently expanded.

So when first reading the element, it's just a bunch of expandable buttons. Then the user expands one, and then when they go onto another they are informed that expanding this button will collapse the previous.

Something like that might be good.

**Comment by holloway** [comment]
I wonder how we should describe the other tab... by index number would be kinda confusing, so I guess we should `.innerText` the other tabs heading and read that out. It could get long.

Why do they need to know another tab has collapsed if they can navigate to the heading and open it again if they want to?

**Comment by CalinDale** [comment]
No need to say which tab will close imo. The user knows which tab they opened, all the accordion needs to say is that it will close.

The user should know the effect of each action they take, there's no reason it shouldn't be communicated to them, not in this case.

Imagine a website has a checkbox form, and for some reason it only lets you see one checkbox option at a time, that's the new fad so you're used to it. You go through the form and check all the options you like, then at the end you discover that it had unchecked every option except the last one you picked. It was a radiobox the whole time and it never told you.

Screenreader users are only shown one item on the page at a time. Whats more they may rely on the content on the page in order to navigate it. Imagine an accordion containing links to different stores in each item. The user finds a store, opens it, finds another store, opens it, decides the previous store was the right one and jumps back to the previous link. Now instead of a link to the store they wanted, they're actually on a link somewhere else on the page because they link they expected to jump to is hidden.

It's just more hassle that people shouldn't have to deal with.

**Comment by holloway** [comment]
Hmm... 

>  there should be a label explaining that expanding one element will collapse another. 

So what wording would you suggest?

We'll need to consider internationalisation of course, so I guess we should have a prop.

**Comment by synecdokey** [comment]
This is a fairly standard pattern, I'd be surprised if it catches anyone off-guard. VoiceOver and Chrome is a fairly buggy combination, but if it's not communicated in other combinations, I'd be wary of adding noise to the pattern as this can also lead to too verbose of an output.

**Comment by CoraDale** [comment]
Ah yup, this is from long ago. I've changed my stance on this sort of thing and I think it's fine to keep as is now.
