### ISSUE TITLE
Timed interval

### ISSUE THREAD

**Issue by garryburch** [springload/react-accessible-accordion#309]
Any way to trigger the items based on setInterval()

**Comment by katie-day** [comment]
Not currently. 

There would be a lot of accessibility considerations for something like this, for example : 
- Users would need to be able to pause the movement because it could make the contents hard to see/read. 
- Changes to open/closed items must be communicated to all users, including screen reader users.
- The keyboard position (“focus”) would need to be managed in a reasonable and comprehensible way.

So I don't believe anything like this will be added in the near future.

**Comment by katie-day** [comment]
Hope that answers your question and I'm just closing this ticket for now, but please reopen to discuss further
