### ISSUE TITLE
checkbox state is lost when expand or closing accordion

### ISSUE THREAD

**Issue by arvind0364** [springload/react-accessible-accordion#313]
https://codesandbox.io/s/react-accordion-expand-test-forked-2ff4g?file=/src/Accordion.js

please take a look at this whether my implementation is correct or I need to maintain the state of checkbox separately.I do need to handle partial check state.

**Comment by katie-day** [comment]
Hi @arvind0364, for accessibility reasons you should not add a checkbox inside a `button`. You will notice the `AccordionItemButton` has a `role='button'` and should not have any interactive elements inside it.

It also looks to me that by adding an `onClick`  to the `AccordionItemHeading` where you then `dangerouslySetExpanded` is somehow causing a re-render and the input also loses it's current state. 

I recommend firstly removing the input from inside the button, and then also remove the onClick from the `AccordionItemHeading` so that only `AccordionItemButton` is controlling expanding/collapsing the accordion panel, so it doesn't cause the 'blinking' when you click another accordion item.

If you do need an input inside the accordion header then `react-accessible-accordion` may not be the best solution. 
However if you would like to explain your needs a bit more, maybe I can help come up with a solution that will work with `react-accessible-accordion`?

**Comment by arvind0364** [comment]
Hi @katie-day thanks for your reply I achieved the desired requirement with some customization like adding a checked stated to the input and updating it in onchange. Yes faced the 'blinking' initially got rid of it by disabling the animation in accordionitemheading.In short am trying build a custom component on my own like 'React-checkbox-tree' with deeply nested list.

**Comment by katie-day** [comment]
@arvind0364 I'm glad you found a way to get the result you were looking for. 
I'm going to close this ticket now, but feel free to open it if you need to discuss further
