### ISSUE TITLE
The length of key and data source are inconsistent.

### ISSUE THREAD

**Issue by wSLecHayfIeNdock** [springload/react-accessible-accordion#64]
[DEMO](https://codesandbox.io/s/n76vv0yvr0)

step.1
In the editor casually modify the content, and then save.

step.2
Click AccordionItem. Pay attention to the change of key.

**Comment by ryami333** [comment]
Gidday @wSLecHayfIeNdock, thanks for trying out react-accessible-accordion. 

Could you please be a little more specific about what you're expecting and what you're seeing instead? I had a bit of a fiddle with the Demo you sent, and I can't really see anything unexpected.

**Comment by wSLecHayfIeNdock** [comment]
![677](https://user-images.githubusercontent.com/16831715/38170231-2e8a23a2-35b2-11e8-8204-9ff6add8a137.gif)

Thank you for your reply.

**Comment by ryami333** [comment]
@wSLecHayfIeNdock there isn't really any relationship between the AccordionItems' IDs (which we call 'uuid's behind the scenes) and React's concept of a `key` prop. If the `uuid` matched those keys, then we'd have issues if there was more than one Accordion in the same application.

If you could actually elaborate on what you're trying to achieve here, then I might be able to help you - but I can't tell what you're actually trying to do simply by viewing your screencapture. Could you please tell me (with detail) what your goal is, what you've tried, what you expected and your results were?

**Comment by wSLecHayfIeNdock** [comment]
@ryami333 Demo updated, Trouble again look at the demo.

AccordionItems id should not be `uuid`. Should be user-defined key.

expected: `key={dataKey}`

```
<Accordion onChange={(dataKey) => {}}>
    <AccordionItem key={dataKey}>
    ...
    </AccordionItem>
</Accordion>
```

**Comment by ryami333** [comment]
I don't know where you've read this - this is not a documented feature of `react-accessible-accordion`. I'm not sure why you're concerned with what we're using as a unique identifier behind the scenes (because you _still_ haven't explained what you're trying to achieve!). We have even used `uuid` generators in the past such as [this one](https://www.npmjs.com/package/uuid) but we've found that we can achieve the same thing by just incrementing an integer.

I don't see any bug here, so I'm going to close this issue until you're able to give a detailed, careful and considered description of the issue that you're facing.

**Comment by wSLecHayfIeNdock** [comment]
I want to get the corresponding data based on the AccordionItem key.
However, the AccordionItem key does not correspond to the data source length.

https://codesandbox.io/s/4wmn3j0y37

**Comment by ryami333** [comment]
@wSLecHayfIeNdock I wonder whether [this issues](https://github.com/springload/react-accessible-accordion/issues/70) is what you were communicate with us here? If so, it would be cool to hear your feedback on whether the proposed solution would suit your needs!
