### ISSUE TITLE
"onChange" action doesn't informative

### ISSUE THREAD

**Issue by epotockiy** [springload/react-accessible-accordion#70]
`onChange` function get only one parameter `uuid` which doesn't informative for outside components, could you replace it by an accordion item index or add this index as the second parameter of the `onChange` function

**Comment by ryami333** [comment]
Gidday @epotockiy - thanks for your issue :)

This feature is actually not quite as trivial as it may seem on the surface. The complexity comes down to the concept of 'order'. In other words, determining which is the 0th (and subsequent) `AccordionItem` in the application.

### Order by... order.
```jsx
<Accordion>
    <AccordionItem>Zero</AccordionItem>
    <AccordionItem>One</AccordionItem>
    <AccordionItem>Two</AccordionItem>
</Accordion>
```
Easy, right? The 0th is the 0th, and the 2nd is the 2nd. In this very simple case, you can use `React.children` to cycle through the *first-generation* children of Accordion, and use the array index as `uuid`.

But what if...

### Order by depth
```jsx
<Accordion>
    <span>
        <span>
            <AccordionItem>Foo</AccordionItem>
        </span>
    </span>
   <AccordionItem>Bar</AccordionItem>
</AccordionItem>
```
So, the problem here is that who's to say whether the 0th AccordionItem here is `Foo` or `Bar`? You might think that the obvious answer is `Foo` because it's the top-most, reading down the DOM. To the next person though, the intuitive answer might be `Bar` because it's closer to the root Accordion item. Whichever way we choose would be somewhat contentious. That's just a minor detail though - whichever way we went, I don't know how we would actually implement this anyway. I'm not sure whether you can actually use `React.children` recursively, and even if you could I would be concerned about performance in large DOM trees.

So, the way we've implemented is more like...

### Order by time
```jsx
class App extends Component {
    render() {
        return (
            <Accordion>
                {loaded && (
                    <AccordionItem>Foo</AccordionItem>
                )
                <AccordionItem>Bar</AccordionItem>

**Comment by epotockiy** [comment]
Yes it is. It would be perfect if you improvement implemented in the nearest future.

**Comment by ryami333** [comment]
Thanks for your feedback @epotockiy - we have this on our roadmap 😄

**Comment by vincentaudebert** [comment]
@epotockiy feel free to contribute with a PR if you want :)

**Comment by vincentaudebert** [comment]
This will go in `v2.4.0`
