### ISSUE TITLE
Closing accordion items on re-render

### ISSUE THREAD

**Issue by ryanwellsdotcom** [springload/react-accessible-accordion#94]
I'm having difficulty closing the open accordion when the component re-renders. Is there an option for this?

**Comment by ryami333** [comment]
Could you please elaborate a little on what you mean by closing on re-render? Perhaps could you paste some code snippets or (even better) a codesandbox example?

**Comment by ryanwellsdotcom** [comment]
If I have an accordion item open, then make a different API call and re-render the accordion items, the previous one that was open remain opened.

**Comment by ryami333** [comment]
This is due to using array index as a key in the map function - the react reconciler doesn't know that it is rendering a totally new `AccordionItem`, it just thinks it's the same one with different content. So, you need to assign a totally unique `key` prop to each `AccordionItem` like in this fork I made of your codesandbox: https://codesandbox.io/s/my2xmonk8x

**Comment by ryanwellsdotcom** [comment]
Ugh, I overlooked the "last resort" section. this resolves it. Thanks!

**Comment by ryami333** [comment]
Cool cool, thanks for coming by :)
